version: '3.5'
services:
  web:
    image: nginx
    ports:
      - 3000:3000
    volumes:
      - /var/www/app
  back:
    image: node
    ports:
      - 3000:3000
    volumes:
      - /var/www/app2
  
