name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: create ENV
      run: |
        touch .env
        echo "test_aslam_image" > .env
        cat .env
    - name: Build Compose File
      uses: isbang/compose-action@v1.4.1
      run: docker-compose -f docker-compose.yml build
    - name: Install doctl 
      run: docker images

        
        
