name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: create ENV
      run: |
        touch .env
        echo "COMPOSE_PROJECT_NAME=my_pro_pro" > .env
        cat .env
    - name: Build Compose File
      run: docker compose -f docker-compose.yml build
    - name: Install doctl 
      run: docker images

        
        
